name: app_financeiro
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  bloc: ^8.1.1
  bloc_test: ^9.1.1
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  mockito: ^5.3.2

flutter:
  uses-material-design: true
